# Site settings
title: "Kayleigh Smith"
url: "https://kayleigh-smith.github.io"
baseurl: ""

# Author information
author:
  name: "Kayleigh Smith"
  title: "PhD student"
  institution: "University of Edinburgh"
  email: "kayleigh.smith@ed.ac.uk"
  orcid: "https://orcid.org/0000-0001-5773-7423"
  researchgate: "https://www.researchgate.net/profile/Kayleigh-Smith-13"
  scholar: "https://scholar.google.com/citations?user=UdpXNiAAAAAJ&hl=en"
  linkedin: "https://linkedin.com/in/kayleighasmith"
  bluesky: "https://bsky.app/profile/kayleighsmith.bsky.social"

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research.md"
  - title: "Publications"
    url: "/publications.md"
  - title: "Teaching"
    url: "/teaching.md"
  - title: "CV"
    url: "/cv.md"
  - title: "Contact"
    url: "/contact.md"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
